# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 橋
email: hsieh.chiao.7k@kyoto-u.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  This is the project to develop 橋.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hc825b.github.io" # the base hostname & protocol for your site
github_username: hc825b
linkedin_username: hc825b
orcid_id: 0000-0001-8339-9915

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-last-modified-at

defaults:
  - scope:
      path: "assets/icons"
    values:
      image: true

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor

header_pages:
  - _pages/projects.md
  - _pages/cv.md
  - _pages/about.md
  - _pages/scribbles.md
  
