# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 橋 Chiao
email: hc825b@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the project to develop Chiao, the view of myself as a computer
  scientist and a researcher.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hc825b.github.io" # the base hostname & protocol for your site
github_username: hc825b

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
logo: https://photos.app.goo.gl/mCqYXquJojj66rVq7
show_downloads: false